import { createAdminClient } from '@/lib/supabase/server'
import { Navbar } from '@/components/layout/Navbar'
import { Footer } from '@/components/layout/Footer'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { TOOL_META } from '@/lib/constants'
import type { Metadata } from 'next'
import { SharePageClient } from '@/components/shared/SharePageClient'

interface Props { params: { id: string } }

async function getGeneration(id: string) {
  try {
    const supabase = createAdminClient()
    const { data } = await supabase
      .from('generations')
      .select('*, users(full_name, avatar_url)')
      .eq('share_id', id)
      .single()
    return data
  } catch { return null }
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const gen = await getGeneration(params.id)
  if (!gen) return { title: 'Result Not Found | AuraForge' }
  const meta = TOOL_META[gen.tool_slug]
  return {
    title: `${meta?.name || 'AI Result'} by AuraForge`,
    description: `Check out this AI-generated result from AuraForge's ${meta?.name}. Try it free!`,
    openGraph: { title: `${meta?.name || 'AI Result'} — AuraForge`, description: 'See what AI discovered!', type: 'website' },
    twitter: { card: 'summary_large_image', title: `My ${meta?.name} Result`, description: 'Try AuraForge free!' },
  }
}

export default async function SharePage({ params }: Props) {
  const gen = await getGeneration(params.id)
  if (!gen) notFound()
  const meta = TOOL_META[gen.tool_slug]

  let result: Record<string, unknown> = {}
  try { result = JSON.parse(gen.output) } catch { result = { result: gen.output } }

  return (
    <>
      <Navbar />
      <main className="pt-24 pb-20 min-h-screen">
        <div className="max-w-2xl mx-auto px-4">
          <div className="text-center mb-10">
            <div className="text-5xl mb-3">{meta?.emoji || '✨'}</div>
            <h1 className="font-display text-3xl font-bold mb-2">{meta?.name || 'AI Result'}</h1>
            <p className="text-muted-foreground">Generated by AuraForge AI</p>
          </div>

          <SharePageClient result={result} meta={meta} shareId={params.id} />

          <div className="mt-10 text-center space-y-4">
            <p className="text-muted-foreground">Want your own AI analysis?</p>
            <Link href={gen.tool_slug ? `/tools/${gen.tool_slug}` : '/tools'}
              className="btn-primary inline-flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-semibold text-white">
              Try {meta?.name || 'this tool'} Free →
            </Link>
            <div className="pt-2">
              <Link href="/" className="text-xs text-muted-foreground hover:text-primary transition-colors">
                auraforge.app — Free viral AI tools
              </Link>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}
