import { Navbar } from '@/components/layout/Navbar'
import { Footer } from '@/components/layout/Footer'
import Link from 'next/link'
import { ArrowLeft, Clock, User, Share2 } from 'lucide-react'
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'

// In production: fetch from Supabase or MDX files
const POSTS: Record<string, {
  title: string
  description: string
  content: string
  author: string
  published_at: string
  tags: string[]
  read_time: number
}> = {
  'how-to-go-viral-on-tiktok-with-ai': {
    title: 'How to Go Viral on TikTok Using AI Tools in 2025',
    description: 'Discover the AI-powered workflow top creators use to consistently produce viral TikTok content.',
    author: 'AuraForge Team',
    published_at: '2025-01-15',
    tags: ['TikTok', 'AI Tools', 'Creator Tips'],
    read_time: 6,
    content: `
## The TikTok Algorithm in 2025

TikTok's algorithm has gotten smarter — and so have the creators winning on it. The secret? They're using AI to front-load the most important element: the hook.

## Why Your First 2 Seconds Matter Everything

Studies show that 65% of viewers decide whether to keep watching in the first 2 seconds. AI hook generators are trained on millions of viral videos and understand exactly what pattern-interrupts work.

## The AI Workflow That's Winning

**Step 1: Generate 10 Hook Variations**

Use AuraForge's Hook Generator with your content idea. Pick the hook with the most tension or curiosity gap.

**Step 2: Scan Your Personality**

Before scripting, use the Personality Scanner to understand your natural creator energy. ENFP creators do well with chaotic, energetic hooks. INTJ creators crush it with counterintuitive takes.

**Step 3: Generate 5 Caption + Hashtag Combos**

TikTok's search is growing. Use the Caption Generator to create SEO-friendly captions that also convert.

**Step 4: A/B Test Titles**

Post the same video twice in the same week with different titles (generated by AI). See which gets more algorithmic push.

## Real Results

Creators using this workflow report:
- 3x increase in video completion rate
- 45% higher follower conversion rate from FYP
- More consistent viral hits (once a week vs once a month)

## Start Today

Head to [AuraForge Creator Toolkit](/tools/creator-toolkit) and run your next video idea through the hook generator. The difference will be immediate.
    `,
  },
  'ai-bio-generator-guide': {
    title: 'The Ultimate Guide to Writing Your Perfect AI Bio',
    description: "Your bio is your first impression. Here's how AI can help you craft one that converts followers.",
    author: 'AuraForge Team',
    published_at: '2025-01-10',
    tags: ['Bio Writing', 'Personal Brand', 'AI'],
    read_time: 4,
    content: `
## Why Your Bio Is Your Most Important Content

You have 150 characters on Instagram. 160 on Twitter. Less than 3 seconds of attention. Your bio either converts a profile visit into a follow — or loses them forever.

## The 3-Part Bio Formula

The highest-converting creator bios follow a simple formula:

**[What you do] + [Who you help/What you make] + [Social proof or personality hook]**

Examples:
- "Travel photographer 📸 | Capturing hidden gems across 40+ countries | Join 200K on this journey"
- "Career coach for Gen Z | Landed 3 Google offers | I teach what universities don't"

## How AI Improves Your Bio

AuraForge's Bio Generator analyzes:
1. Your niche and content style
2. Your target audience
3. Your key differentiators
4. Platform-specific character limits

Then it generates 4 versions optimized for each platform: Instagram, TikTok, Twitter/X, and LinkedIn.

## Common Bio Mistakes AI Fixes

- **Too vague**: "Content creator" → "Minimalist lifestyle creator helping busy people live with less"
- **No CTA**: Adding "↓ Free guide in link" increases link clicks by 34%
- **Missing personality**: Professional doesn't mean boring. AI finds the balance.

## Try It Now

Go to [AI Creator Bio Generator](/tools/creator-toolkit) and paste a description of yourself. In 10 seconds, you'll have 4 optimized bios ready to copy.
    `,
  },
}

interface Props {
  params: { slug: string }
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const post = POSTS[params.slug]
  if (!post) return { title: 'Post Not Found' }

  return {
    title: `${post.title} | AuraForge Blog`,
    description: post.description,
    openGraph: {
      title: post.title,
      description: post.description,
      type: 'article',
      publishedTime: post.published_at,
      authors: [post.author],
      tags: post.tags,
    },
    twitter: {
      card: 'summary_large_image',
      title: post.title,
      description: post.description,
    },
  }
}

export default function BlogPostPage({ params }: Props) {
  const post = POSTS[params.slug]
  if (!post) notFound()

  // Convert simple markdown-like content to HTML paragraphs
  const renderContent = (content: string) => {
    return content.trim().split('\n').map((line, i) => {
      if (line.startsWith('## ')) return <h2 key={i} className="font-display text-2xl font-bold mt-10 mb-4">{line.slice(3)}</h2>
      if (line.startsWith('**') && line.endsWith('**')) return <p key={i} className="font-semibold my-2">{line.slice(2, -2)}</p>
      if (line.startsWith('- ')) return <li key={i} className="ml-4 text-muted-foreground">{line.slice(2)}</li>
      if (line.trim() === '') return <br key={i} />
      return <p key={i} className="text-muted-foreground leading-relaxed mb-3">{line}</p>
    })
  }

  return (
    <>
      <Navbar />
      <main className="pt-24 pb-20">
        <div className="max-w-3xl mx-auto px-4">
          <Link href="/blog" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors">
            <ArrowLeft className="w-4 h-4" /> Back to Blog
          </Link>

          {/* Tags */}
          <div className="flex gap-2 mb-4 flex-wrap">
            {post.tags.map(t => (
              <span key={t} className="text-xs px-2.5 py-1 rounded-full bg-primary/10 text-primary font-medium">{t}</span>
            ))}
          </div>

          {/* Title */}
          <h1 className="font-display text-3xl sm:text-4xl font-bold mb-4 leading-tight">{post.title}</h1>

          {/* Meta */}
          <div className="flex items-center gap-4 text-sm text-muted-foreground mb-8 pb-8 border-b border-border">
            <span className="flex items-center gap-1.5"><User className="w-4 h-4" />{post.author}</span>
            <span className="flex items-center gap-1.5"><Clock className="w-4 h-4" />{post.read_time} min read</span>
            <span>{new Date(post.published_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</span>
          </div>

          {/* Content */}
          <article className="prose-custom space-y-1">
            {renderContent(post.content)}
          </article>

          {/* CTA */}
          <div className="mt-12 p-6 rounded-2xl bg-primary/5 border border-primary/20">
            <h3 className="font-display font-bold text-lg mb-2">Try AuraForge Free</h3>
            <p className="text-muted-foreground text-sm mb-4">10 free AI generations every day. No credit card needed.</p>
            <Link href="/tools" className="btn-primary inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold text-white">
              Explore AI Tools →
            </Link>
          </div>

          {/* Share */}
          <div className="mt-8 flex items-center gap-3">
            <span className="text-sm text-muted-foreground">Share this article:</span>
            <a
              href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(post.title)}&url=${encodeURIComponent(`https://auraforge.app/blog/${params.slug}`)}`}
              target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border text-sm hover:border-primary/30 transition-colors"
            >
              <Share2 className="w-3.5 h-3.5" /> Share
            </a>
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}

export async function generateStaticParams() {
  return Object.keys(POSTS).map(slug => ({ slug }))
}
